### ISSUE TITLE
Save Images

### ISSUE THREAD

**Issue by Chipperchap** [AntonyCorbett/OnlyV#1]
Hi Andrew,

**Thank you so much for the new application!**

A query if I may please.  We used to be able to save bible text images to any desired folder via the ShortCut Manager.  I would save it to the cloud (OneDrive) for our sign language laptop to also have access to the images.  It has been a while since I did this and had a quick look... however I cannot see how OnlyV will work in that situation (since it is not 'SoundBox' anymore).  Am I correct?

I have a workaround - I use 'Allway Sync' to create a copy of the images saved to 'OnlyV - Bible Text Images' folder into the cloud (OneDrive) for our remote laptop access.  Should I just continue with that?

Looking forward to being able to change the font style soon... (smile).

Kind regards
Simon

**Comment by blazer2004** [comment]
OneDrive should already be uploading your images to the cloud, by virtue of the image folder being in a default sync folder. It just needs to be shared with your ASL computer. Navigate to your OnlyV folder, find the image folder, and right click the image folder and select one of the OneDrive Share options. This should get you on your way. Suggestion- be sure both your computer and the target computer are running the lastest copy of OneDrive.  Hope This Helps

**Comment by AntonyCorbett** [comment]
@Chipperchap No, there's no way to change the folder. However, there are a number of workarounds sucha s that suggested by @blazer2004
