### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by fprietorossi** [AntonyCorbett/OnlyV#13]
You have considered having translations for this program, just like what has been done in OnlyT and OnlyM?

**Comment by AntonyCorbett** [comment]
@fprietorossi Yes. I'll set it up soon. But just waiting for the localisation work on OnlyM and OnlyT to reach a steady state first!

**Comment by gonzo041** [comment]
Hi Antony,
Was there any progress with the translation into Spanish?

**Comment by AntonyCorbett** [comment]
@gonzo041 No, I haven't started a translation project for OnlyV yet, but thanks for the reminder. I will try to set aside some time soon.
