### ISSUE TITLE
Controlling OnlyT from remote device 

### ISSUE THREAD

**Issue by KJB68** [AntonyCorbett/OnlyV#14]
Can OnlyT be controlled by a remote device such as your tablet or phone like SoundBox could?

**Comment by richfrantz** [comment]
https://play.google.com/store/apps/details?id=com.imattsolutions.onlyt



________________________________

**Comment by AntonyCorbett** [comment]
@KJB68 yes. Please see @richfrantz link above. Also please read the project wiki.

**Comment by KJB68** [comment]
Thank you! 
 
 
 
 
-------Original Message-------
 
From: Antony Corbett
Date: 12/11/2018 1:50:44 PM
To: AntonyCorbett/OnlyV
Cc: KJB68;  Mention
Subject: Re: [AntonyCorbett/OnlyV] Controlling OnlyT from remote device
(#14)
 
@KJB68 yes. Please see @richfrantz link above. Also please read the project
wiki.

**Comment by KJB68** [comment]
Thank you! 
 
 
-------Original Message-------
 
From: richfrantz
Date: 12/11/2018 1:41:13 PM
To: AntonyCorbett/OnlyV
Cc: KJB68;  Author
Subject: Re: [AntonyCorbett/OnlyV] Controlling OnlyT from remote device
(#14)
 
https://play.google.com/store/apps/details?id=com.imattsolutions.onlyt



________________________________
