### ISSUE TITLE
Justify option

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyV#15]
First thanks @AntonyCorbett for all the hard work while providing and supporting such software (all OnlyX suite) which makes AV operators life easier.
Would be nice if OnlyV will have an option for justify alignment but I don't know how if that's possible or hard to implement, so it's up to you.
I personally liked the layout used here even if text is aligned on left. https://tv.jw.org/#en/mediaitems/LatestVideos/pub-bhat_x_VIDEO
I don't know if it's possible to have an option to move the title text on top right and have a line to break the title and body text. If it's not to much for you I can raise a new request but if it's too complicate probably doesn't worth the effort.
Thanks again for all your efforts, they are really appreciated.

![vers](https://user-images.githubusercontent.com/45002147/50575836-27b4c480-0e0e-11e9-8469-ccfd73141968.png)

**Comment by LvDaniel** [comment]
@AntonyCorbett sorry, I haven't noticed the position option for the title text. Just the line is missing, but I can we can live with that.

**Comment by LvDaniel** [comment]
@AntonyCorbett is it possible to have all the book name for example Exodus, not Ex. since we have enough space for that? I'll create another request if it's ok for you.

**Comment by AntonyCorbett** [comment]
@LvDaniel Please feel free to create feature requests. That way we can document / discuss, even if I decide not to do anything immediately.

**Comment by LvDaniel** [comment]
@AntonyCorbett, thanks. I'll do that and close this one.
