### ISSUE TITLE
JW Library Year Text sometimes will not display after displaying a scripture and stoping

### ISSUE THREAD

**Issue by japennell** [AntonyCorbett/OnlyV#18]
We noticed that often, when we open a scripture and display it on the monitors, then close the scripture, the monitors will resume to show only the black native background and the JW logo in the lower right corner of the JW Library Year Text screen with NO year text.

However, if we repeat the above step by again selecting the scripture to display and then close the display a second time, often the black background, jw logo in the lower right AND THE YEAR TEXT display correctly.

**Comment by AntonyCorbett** [comment]
@japennell This can sometimes be reproduced just by opening and closing the JW Library media window from teh taskbar (i.e. without any other applications involved). Updating your video driver may help.

**Comment by japennell** [comment]
Thank you for the quick reply.  We will try that.

YB

Jason
