### ISSUE TITLE
Option to display full book name

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyV#19]
Would be nice to have an option to display full book name instead of abbreviation.

![full name](https://user-images.githubusercontent.com/45002147/50938042-16f3f680-147f-11e9-87dc-9bd2987ed9a0.png)

**Comment by AntonyCorbett** [comment]
@LvDaniel done

**Comment by LvDaniel** [comment]
@AntonyCorbett you're great. Thank you very much for your kindness and help.
