### ISSUE TITLE
No Theme Selection

### ISSUE THREAD

**Issue by Chipperchap** [AntonyCorbett/OnlyV#2]
For some strange reason, when I loaded OnlyV on my home PC, I have nine themes to choose from for the ***Image Style***; however when I loaded OnlyV on the Kingdom Hall computer there is only ***Default*** to choose from.  They are both version 1.0.0.4 and the settings are identical.  I have removed and re-downloaded several times to no change.
Very curious.

**Comment by AntonyCorbett** [comment]
@Chipperchap thanks I think I can see the problem. The installer places the themes in the user's "Documents\OnlyV" folder but the installing user may or may not be the same as the regular user.

**Comment by Chipperchap** [comment]
I worked out a work-around by just copying the contents of the _**ThemeFiles**_ from my PC into the KHall PC and it worked.

By the way, is there a way to 'modify' one of those files so that it will display the scriptures the same way that we are familiar with (according to the preferences set up) with the SoundBox Bible Text Image Generator?

**Comment by EfrenAvilaJr** [comment]
Can we use our own background images???

**Comment by Chipperchap** [comment]
Not that I know of, hence why the query I made above...

**Comment by AntonyCorbett** [comment]
@Chipperchap @EfrenAvilaJr Theme editor coming soon

**Comment by AntonyCorbett** [comment]
Fixed

**Comment by EfrenAvilaJr** [comment]
Awesome, thx Antony
