### ISSUE TITLE
Space between book name and text body

### ISSUE THREAD

**Issue by LvDaniel** [AntonyCorbett/OnlyV#23]
@AntonyCorbett if it's not too much to ask, is it possible to adjust the space size between the book name and text body, for not occupying so much space? If this complicates things, don't worry is not something very important, just a nice to have.

And I want to thank you very much for implementing all the other features so promptly. May Jehovah bless all the efforts and time spent for providing such wonderful tools.

![space name body](https://user-images.githubusercontent.com/45002147/51060552-c7d1d100-15f8-11e9-99e8-fd33fe58d3fd.png)

**Comment by AntonyCorbett** [comment]
Perhaps you'd share your theme?

**Comment by AntonyCorbett** [comment]
@LvDaniel made adjustment to algorithm that calculates space between title and body

**Comment by LvDaniel** [comment]
@AntonyCorbett that's perfect! Thank you very much.

I don't know if is still needed, but below is my theme.
[ThemeDarkGreyJW.zip](https://github.com/AntonyCorbett/OnlyV/files/2752040/ThemeDarkGreyJW.zip)

**Comment by AntonyCorbett** [comment]
@LvDaniel thanks - I can perhaps add it to the supplied themes

**Comment by LvDaniel** [comment]
@AntonyCorbett that would be great.
I've add it below with minor updates.
[DarkGreyJW_v2.zip](https://github.com/AntonyCorbett/OnlyV/files/2752500/DarkGreyJW_v2.zip)
