### ISSUE TITLE
Theme Blur Bible

### ISSUE THREAD

**Issue by flowereight** [AntonyCorbett/OnlyV#24]
Hi, I've created a theme that represents a blurry bible. Can it be included in the default installation? Best.
[OnlyV Bible Blurry.zip](https://github.com/AntonyCorbett/OnlyV/files/2952688/OnlyV.Bible.Blurry.zip)

**Comment by AntonyCorbett** [comment]
@flowereight Thanks for the theme, and sorry for the delay in responding. Couple of questions please:
1. Do we have rights to use the background image?
2. Could you provide a similar theme but with the image less blurred please?

**Comment by flowereight** [comment]
Dear brother,

I created the blurred image and I no longer find the original non-blurred
file.

Best.
-- 
Alessandro Fiorotto
alex@fiorotto.com


Il giorno sab 18 mag 2019 alle ore 09:39 Antony Corbett <
notifications@github.com> ha scritto:

**Comment by AntonyCorbett** [comment]
@flowereight ok, thanks. I just thought the image would be better slightly less blurred.
