### ISSUE TITLE
Font used in Modern Grey theme

### ISSUE THREAD

**Issue by timjobutler** [AntonyCorbett/OnlyV#25]
Hi,

I am creating a couple of images with text for a upcoming public talk. I have save all the images for my scriptures using the _OnlyV Modern Grey_ theme.

For consistency, I would like to replicate the same details from _OnlyV Modern Grey_ theme on the images I am creating. I have identified the colours but unable to identify the font used for the text.

Is it possible to have some assistance with identifying the font please?

Thank you kindly,
Tim

**Comment by LvDaniel** [comment]
@timjobutler font used is Segoe UI.

**Comment by timjobutler** [comment]
@LvDaniel Thank you so much for your help

**Comment by AntonyCorbett** [comment]
@timjobutler you can always open the theme in the theme editor.

**Comment by timjobutler** [comment]
@AntonyCorbett Good point. I tried to open the theme in the editor but I could not locate the themes. The Wiki states they are stored in

> CommonAppData\OnlyV\ThemeFiles

 but when I check there were no files. My user account has admin privileges so they should be installed.

Am I looking in the wrong place?

**Comment by LvDaniel** [comment]
@timjobutler built in themes are located here: C:\ProgramData\OnlyV\ThemeFiles
New created themes will be stored on C:\Users\Administrator\Documents\OnlyVThemeCreator

**Comment by timjobutler** [comment]
Thanks @LvDaniel. I found the user created themes but the built-in themes I could not.

Would the Wiki article [https://github.com/AntonyCorbett/OnlyV/wiki/Theme-Creator](url) need to be updated with this location for the built-in themes?

**Comment by LvDaniel** [comment]
@timjobutler CommonAppData is normally C:\ProgramData. Probably this folder can be changed so I guess that's why Antony did't included the path.

**Comment by AntonyCorbett** [comment]
@LvDaniel @timjobutler It's technically ok, but @timjobutler is right - better changed. Done.
