### ISSUE TITLE
Suggestion: Free text instead of scripture

### ISSUE THREAD

**Issue by timjobutler** [AntonyCorbett/OnlyV#26]
Hi,

I would like to ask if there would be any consideration, either now or in the future, given to enhancing OnlyV to allow for free text to be entered instead of scripture. Some images I create images containing text only but have to make the image from scratch, both content and formatting, using an online design tool.

It would be great to utilise the formatting and styling of a theme (standard or custom) to free text.

I have no idea about the complications and effort involved but wanted to ask the question.

Many thanks for a wonderful product Anthony.

Kind regards,
Tim

**Comment by AntonyCorbett** [comment]
@timjobutler you can edit the text of a verse and replace all of the text with your own. This is a bit of a hack but may work ok for you.

**Comment by timjobutler** [comment]
@AntonyCorbett Okay, this sounds good. I turned on this option and was able to edit the verse text only. Is it possible to modify this option or create an additional option to allow the edit of the scripture?

Regarding the verse editing function, is it feasible to allow line breaks to be added?

Just asking the questions and happy to be told no if the effort does not justify the outcome.

Thanks Antony.

**Comment by AntonyCorbett** [comment]
@timjobutler you'd need to turn off the display of the title (book, chapter, verse). Unfortunately, there's no way to insert a line break atm.

**Comment by AntonyCorbett** [comment]
@timjobutler To create a really useful 'free-text' version would require considerable redesign and I think it would be a departure from the core purpose of the app - sorry.
