### ISSUE TITLE
Recognition of new characters.

### ISSUE THREAD

**Issue by gonzo041** [AntonyCorbett/OnlyV#28]
Hi Antony,
I wanted to check if there is a possibility that OnlyV will recognize the character: g̃, which is shown in the photo:
![Mateo 17-4 (OnlyV)](https://user-images.githubusercontent.com/41997628/57423280-bc2e9980-71e9-11e9-9441-5e05e6dbdbf3.JPG)
![Mateo 17-4 (JW Library)](https://user-images.githubusercontent.com/41997628/57423281-c2bd1100-71e9-11e9-9a87-b8013563bf72.JPG)
Thank you
Best regards

**Comment by AntonyCorbett** [comment]
@gonzo041 What language is it please?

**Comment by gonzo041** [comment]
The language is Guarani

**Comment by AntonyCorbett** [comment]
@gonzo041 Thanks. The Georgia font (used in the "OnlyV Bible" theme) does not include that character. Use the OnlyV Theme Creator to modify the font that is used.
