### ISSUE TITLE
Integration from OnlyV into OnlyM

### ISSUE THREAD

**Issue by Chipperchap** [AntonyCorbett/OnlyV#3]
Hi Antony,
Last night was the first time I tried to use JWL and the various Only'X' tools.  The first time we haven't used SoundBox for a couple of years!  
One thing, if I may please, I found was that there is no ability to drag an image from OnlyV into OnlyM as we used to be able to do with the SoundBox Bible Text Image Creator tool, to save a scripture, or a series of scriptures for later display.  For example if I wanted to preload the TFGW and Digging scriptures.  Rather the scriptures need to be saved and then dragged into the OnlyM folder from the OnlyV folder.  Just curious.... is that by design?  Why I ask is because there is the 'copy to clipboard' feature but that generated image is not able to be pasted into OnlyM either (software or folder).
My workaround would be to use a sync tool to automatically send saved scriptures into the OnlyM folder for later rendering/displaying.  
It is also interesting that several verses are turned into a folder with OnlyV which, as a folder, OnlyM cannot render.  But several verses created in SBTICreator will send them over (via a sync tool) as individual images which of course OnlyM will display.  
The challenge with SBTICreator is that it will not 'Display' images on a secondary screen (eg. auditorium screens) unless SB is open... but OnlyV will which is great for 'live' images (verses that are chosen for display at/on the current moment).
What I do like about OnlyM is the feature to render images using crossfade, both when displaying and when hiding the display.  OnlyV will 'crossfade' to display the scripture, but will 'cut' when hiding... making its disappearance rather abrupt.
I guess we will just have to figure out locally what our preferences are, working within the parameters of each piece of software to best suit our needs (or wants!)

**Comment by AntonyCorbett** [comment]
@Chipperchap Thanks for feedback. Please would you create a new issue for your comments regarding "cross-fade"?

**Comment by mbastet** [comment]
Would be nice to be able to choose the save folder in Only-V.
That way we could save the scripture png right into the Only-M folder.

**Comment by AntonyCorbett** [comment]
@mbastet You can do so now using a symbolic link (requires a little Windows know-how).

**Comment by AntonyCorbett** [comment]
@Chipperchap @mbastet The latest versions of OnlyM (pre-release) and OnlyV offser support for this. Use drag and drop from OnlyV into OnlyM to create a multi-image "slideshow".

**Comment by Chipperchap** [comment]
Just confirming that we tried this feature yesterday and it is working fine.  👌

Just a note for my future reference (not a bug): the user cannot create a bracket of scriptures in OnlyV (for example: John 2:1-4 - which becomes an images folder ) and press the 'save' button for a symbolic link (or in my case auto folder sync software) to transfer this to OnlyM for multi-image 'slide-showing'.  The folder (with John 2:1-4 images) will transfer but will not display in the playlist of OnlyM.  

When using drag-n-drop from OnlyV to OnlyM however, it will automatically open the folder and list the scriptures (images) individually for 'slide-show'. 😎
