### ISSUE TITLE
Display format Question

### ISSUE THREAD

**Issue by KenFrantz** [AntonyCorbett/OnlyV#30]
Just a question, no work expected. Is it possible to create ones own display template? Is there any documentation?

Ken

**Comment by AntonyCorbett** [comment]
@KenFrantz Yes. The OnlyV Theme Creator is a separate application which is installed along with the OnlyV application.

**Comment by KenFrantz** [comment]
Yes, I have used that. But it doesn't allow moving the title text such that it would appear to the left or the right of the body text. Only above or below. I'd like to see the title text to the left, similar to the way the Pure Worship book displays scripture texts in the introduction videos.

If it can't be done, I can just make my own jpegs and display them with only. I was just wondering, that's all.

Thanks for your reply.

Ken
C: (518) 947-4709

________________________________

**Comment by AntonyCorbett** [comment]
@KenFrantz You're correct, there is no way to configure the theme to display teh title in the left or right margin.
