### ISSUE TITLE
Text Scaling

### ISSUE THREAD

**Issue by KenFrantz** [AntonyCorbett/OnlyV#31]
The text scaling feature seems to add a degree of confusion. If I choose a 80pt font, the scale allows me to go larger or smaller. How do I know when I'm seeing 80pt. font on the screen? If I want larger or smaller characters, can't I just choose a larger or smaller font? 

I can see where the scaling might be advantageous, but an index on the scale to show where the scale actually matches the font size would make things less tedious. Maybe put a zero marker in the center of the scale to indicate true font size, as selected in the theme creator, and then allow scaling up and down from center. I can do that in the tool as it is now, but then I always have to remember to set the scale every time I change templates.

**Comment by AntonyCorbett** [comment]
@KenFrantz Sorry for the delay in responding. Just to summarize this feature request:

Font sizes for the various elements are specified in the theme. In addition, OnlyV provides a "Font scaling" feature that can be used to uniformly scale up or down the size of all fonts. The scaling function uses a slider where the midpoint represents no scaling. It would be useful to make the midpoint clearer, and the scaling should be reset when a new theme is selected.

**Comment by AntonyCorbett** [comment]
@KenFrantz done in latest pre-release (button resets to 100% scaling)
