### ISSUE TITLE
Theme Creator

### ISSUE THREAD

**Issue by paoloramos** [AntonyCorbett/OnlyV#6]
Hi Anthony,

I can't seem to find the theme creator. Would you mind pointing me to the right direction?

Thanks,
Paolo

**Comment by tomtailor1983** [comment]
Hi Paolo!

1st way: You have a link on your desktop.
OR
2nd way: Start "C:/%program data%/OnlyV/OnlyV Theme Creator.exe" (i don't know the name exactly).

Records, Alex

**Comment by paoloramos** [comment]
@tomtailor1983 : saw it! How can I miss it!!! Thanks!

**Comment by AntonyCorbett** [comment]
%ProgramFiles(x86)%\OnlyV\OnlyVThemeCreator.exe
