### ISSUE TITLE
Improve naming of images which represent multiple verses in the same passage

### ISSUE THREAD

**Issue by GregWoods** [AntonyCorbett/OnlyV#76]
This use-case is when using OnlyV to create scripture png files, then using OnlyM to display them.

When creating verses from OnlyV, I copy/paste the verse png files from my OnlyV/BibleTextImages folder to my OnlyM folder. It generally works really well.
However, when scriptural passages contain many verses, they are split onto several slides and put into their own folder.

The problem is that OnlyM ignores anything inside a subfolder, so my simple copy/paste doesn't work
One fix would be a change to OnlyM, but it would likely need a new UI to handle "stacked" slides of the same Bible passage.

A simpler solution is to change the way OnlyV exports these related images.

1) Don't store them in subfolders, since OnlyM cannot handle these folders
2) Change the naming so that the 001, 002, 003 etc is at the end of the filename instead of the beginning. 

With the naming scheme as it is, even if I manually move the files out of the subfolders, they are now listed in a bizarre order, where all the unrelated 001 images are listed together, then all the 002 images. It can be fixed by manually renaming, but a simple-ish change to the way OnlyV names the files would help a lot. I would propose adding the 001 002 etc modifier onto the end of the filename instead prefixing it.

Of course, there may be other use-cases, particularly when using the F5 (display) option, which i'm not taking into account.

**Comment by AntonyCorbett** [comment]
@GregWoods I suggest you use the OnlyM slideshow feature. Drag and drop from OnlyV to automatically create one.

**Comment by GregWoods** [comment]
Fantastic! That was exactly how I'd expect the UI to look for multiple-slide verses :)
