### ISSUE TITLE
Application keeps crash when generating multi Thai verses wallpaper.

### ISSUE THREAD

**Issue by DhitiBank** [AntonyCorbett/OnlyV#77]
Dear developer

Thank you for your application. It helps me a lot especially right now when every one do meeting by video conference. I'm Thai so please forgive me if there is any mistake with my writing.

I added bible Thai and English version (epub) to the app. It works fine for English, but there is some problem with Thai. When I tried to select more than one verse, the app stop working and close itself. I also attach log file with this post.

My OS is Windows 10 Home version 1909 (build 18363.836)

Sincerely

Dhiti T
[log-20200517.txt](https://github.com/AntonyCorbett/OnlyV/files/4639814/log-20200517.txt)

**Comment by AntonyCorbett** [comment]
@DhitiBank Thanks for your report. I have reproduced the problem and should be able to investigate later today.

Regards
Antony

**Comment by AntonyCorbett** [comment]
@DhitiBank This happens when a single word is too long to render within the width of the image. I have fixed in the latest release. It now shows a warning with a suggestion to reduce the text font size (see text scaling in settings).

**Comment by DhitiBank** [comment]
@AntonyCorbett  Thank you very much for your latest update. It works now!
