### ISSUE TITLE
NWT.epub download?

### ISSUE THREAD

**Issue by mpompey** [AntonyCorbett/OnlyV#79]
Not sure if this is the right place to add a question, but where do we download an epub of NWT? I dont see a link where I can download an epub for use in a 3rd party e-reader or tool. I was looking into using this app to create the test overlays for a sister's memorial, vs doing it in GIMP.

Any help or links to where I can get a current NWT.epub would be appreciated.

**Comment by AntonyCorbett** [comment]
@mpompey 

https://www.jw.org/en/library/bible/

Choose the download icon and pick "EPUB". It's not available for the Study Edition - just use the 2013 revision.

Regards,
Antony
