### ISSUE TITLE
Show bibletext without preview mask.

### ISSUE THREAD

**Issue by tomtailor1983** [AntonyCorbett/OnlyV#8]
I wish me a quickmode like this:
- choose book, chapter and vers
- push a button "to Projector" in the same mask
- choose new vers's and replace the original (with crossfade) with a second button.
- next/previous buttons for long text were avaiable...
- Is the button "to Projector" switch off you can fade out and show jw libary.

Its only a wish... :)

**Comment by AntonyCorbett** [comment]
@tomtailor1983 thanks for the suggestion. It sounds like a more streamlined approach but having considered what refactoring would be needed I don't think the effort is warranted. Sorry I have to be so ruthless with some of the requests - I'm nmost grateful for your valuable feedback!
