### ISSUE TITLE
Save Multi-Image Verses directly to ".OMSlide"

### ISSUE THREAD

**Issue by Gaza84** [AntonyCorbett/OnlyV#83]
thank you for Both OnlyM and OnlyV! they help us tremendously! This is not an Issue but rather a feature suggestion/request I'm not sure if this would benefit anyone else, but we often Save the verses we will be sharing at the meeting ahead of time then display them with OnlyM. This helps be sure we have no errors especially when the meeting schedule is particularly busy 

when there are more than one image generated for longer bible passages, we will create a slide using OnlyM Slide manager. It would be very convenient if there were an option on OnlyV to save directly to ".OMSlide" 

This would very much be a "luxury" feature, so if it represents a considerable amount of effort, please feel free to disregard this suggestion

thanks!
Garth

**Comment by AntonyCorbett** [comment]
@Gaza84 You can drag and drop from OnlyV into OnlyM - it automatically creates the slide

**Comment by Gaza84** [comment]
Thank you, i was not aware that worked like that! Thats perfect, it will make things so easy :)
