### ISSUE TITLE
Ability to display Talk Themes (and Announcements)

### ISSUE THREAD

**Issue by DanJermy** [AntonyCorbett/OnlyV#9]
I've been asked if we could display the Public Talk Title on the screens.

One possible approach to achieve this was to create images for all the talk titles (c.190) which I could then link to a folder and shortcut to Only-M, however that suggests a limit of 50 images in the list.

It would be more useful to be able to add text 'ad-hoc' to be displayed in the same way that OnlyV does, which could be done easily by the sound brother just before the meeting.

As a separate but connected use case:   I've also seen some congregations display announcements before and after the meeting (using what must have been powerpoint) to avoid taking up time during the midweek meeting to notify of standard schedule items and other general announcements;  this might be a useful way to quickly display notices as the brothers request.
... Many thanks

**Comment by AntonyCorbett** [comment]
@DanJermy how does this sit with the direction regarding displaying the year text before and after the meeting?

**Comment by DanJermy** [comment]
Yes I did wonder about that myself. Perhaps the other congregation I saw that in don’t do that anymore since the letter. Does the letter offer any room to include additional elements on the display or does it indicate the year text must stand alone?

Separate to that, the letter should have no bearing on the potential feature to display a talk title throughout a public talk - would you agree?

**Comment by AntonyCorbett** [comment]
@DanJermy >letter should have no bearing on the potential feature to display a talk title throughout a public talk - would you agree?<

Agreed, but perhaps the public speaker would determine what, if any, media was displayed during the talk itself. In the end it's up to local elders to decide on the matter, but it would seem unwise to spend time and effort on questionable features when there are more patent gaps to fill. Just my personal view :)

BTW, I understand the letter regarding media playback is available in the "forms" section of jw.org.

Thanks for your valuable input Dan!

**Comment by DanJermy** [comment]
Thanks Antony.
Agree with all those sentiments.  Just thought I would call it out as a
couple of speakers specifically asked for the capability, and (as with all
requests no doubt) it doesn't seem like too big a challenge to allow manual
entry instead of epub as a data source.
Perhaps one of those 4th quadrant items :) Will leave with the good
judgement of you coding folks!
