### ISSUE TITLE
delete incorrect epub file added to only V 

### ISSUE THREAD

**Issue by tdhc13** [AntonyCorbett/OnlyV#97]
Greetings Brother: 

I was seeking to add another language epub file to our Only V but ended up adding the wrong epub files twice before I got it right. Is there a way to delete these unwanted files? I tried deleting the app and downloading it again but the unwanted epub files remain in the new program.

**Comment by AntonyCorbett** [comment]
@tdhc13 Thanks for your report. I will investigate.

**Comment by AntonyCorbett** [comment]
@tdhc13 It's a simple solution. Open the Documents\OnlyV\SourceEpubFiles folder in Windows and delete the files you don't want. Restart OnlyV

**Comment by tdhc13** [comment]
Okay. Got it. Thank you brother.
